### PR TITLE
Include labels/images defined in item info

### PR DESCRIPTION
**Pull request by T3mpu5**

### CODE REVIEW

**Comment by T3mpu5** [comment]
image
image

**Comment by jimathy** [comment]
So, I'm confused by this (and it's early for me)

What does this exactly do? I see its grabbing the info from the products, but is that a thing?

It tries to grab the information from `QBCore.Shared.Items` and if it can't find it, hides the button.
Is this just a long way around that?

**Comment by T3mpu5** [comment]
So, probably not many people will use this as most are scared of metadata(item info) xD

What this does is first look through the metadata to see if a custom image/label is defined there and then displays that.

For example, in my script I have 3 items; tradingcard, boosterpack, album. But you can have u limited variations of them by changing the metadata. So you can see the screenshot I have a pokemon booster pack. But then using the same item I could have a YuGiOh booster pack.

Hope this makes sense xD

**Comment by jimathy** [comment]
Oh interesting, basically an all in one item
instead of having 5 different booster pack items, just rely on the metadata

I mean. If it doesn't effect anything else I'm happy to include it

**Comment by T3mpu5** [comment]
Yeah, it's more for the cards though as there's like 180 in the included set, then like 15 dlc sets.... Someone had 1200 card items alone xD

But yeah, that'd be ace. Thank you

**Pull request merged**
